# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c49974044c0f85e08ae9bd6aff2b6e94d81159ead5f05311b10afb286aca75769bf81ae472469cc8bc48caa825d2d6a429c3f78942ec440ac52f918b0d4253c

test:
  secret_key_base: 339511d4556e7b2ac9304b2e3390f8a47ada74358b379dbfaf3bd22deea18c10f109d8fa46b2c69d20792f4b8bee054c1599060e88cf7daf7a281ef5bc3a6366

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
